### ISSUE TITLE
Installed gem version is not match with dependencies.

### ISSUE THREAD

**Issue by shuLhan** [webis-de/wikipedia-vandalism-detection#2]
I'm new to JRuby, so please excuse me if this issue is either related to my environment only, or lack of `Gemfile.lock` file in source repository.

Steps to reproduce,
- Install gem for wikipedia-vandalism_detection
  
  ```
  $ jruby -S gem install wikipedia-vandalism_detection
  ```
- create `config/config.yml`
- create main script `main.rb`, which content is only one require to wikipedia gem,
  
  ```
  require 'wikipedia/vandalism_detection'
  ```
- run the script
  
  ```
  $ jruby main.rb
  ```

Result,

```
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 1.7.7, ~> 1.7, ~> 1.8)
      minitest (~> 5.1)
      rake (>= 0)
      test-unit (>= 0)
      rdoc (>= 3.12)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Bundler::GemNotFound: Could not find i18n-0.6.1 in any of the sources
   block in materialize at /home/ms/.gem/ruby/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:92
                   map! at org/jruby/RubyArray.java:2332
            materialize at /home/ms/.gem/ruby/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85
                  specs at /home/ms/.gem/ruby/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:140
                  specs at /home/ms/.gem/ruby/2.2.0/gems/bundler-1.10.6/lib/bundler/environment.rb:22
  populate_dependencies at /home/ms/.gem/ruby/2.2.0/gems/jbundler-0.4.3/lib/jbundler/gemfile_lock.rb:46
                  <top> at /home/ms/.gem/ruby/2.2.0/gems/jbundler-0.4.3/lib/jbundler.rb:39
                require at org/jruby/RubyKernel.java:939
                require at /opt/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:69
                  <top> at /home/ms/.gem/ruby/2.2.0/gems/ruby-band-0.1.13/lib/ruby-band.rb:1
                require at org/jruby/RubyKernel.java:939
                require at /opt/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:69
                  <top> at /home/ms/.gem/ruby/2.2.0/gems/ruby-band-0.1.13/lib/ruby-band.rb:3
                require at org/jruby/RubyKernel.java:939
                require at /opt/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:69
                  <top> at /home/ms/.gem/ruby/2.2.0/gems/wikipedia-vandalism_detection-0.0.1/lib/weka/classifiers/meta/one_class_classifier.rb:1
                require at org/jruby/RubyKernel.java:939
                require at /opt/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:69
                  <top> at /home/ms/.gem/ruby/2.2.0/gems/wikipedia-vandalism_detection-0.0.1/lib/weka/classifiers/meta/one_class_classifier.rb:2
                require at org/jruby/RubyKernel.java:939
                 (root) at /home/ms/.gem/ruby/2.2.0/gems/wikipedia-vandalism_detection-0.0.1/lib/wikipedia/vandalism_detection/configuration.rb:1
                  <top> at ./main.rb:1
```

The only way to fix this by installing specific version manually, i.e. `jruby -S gem install i18n -v 0.6.1`, but it will result with another required gem version, for example after I installed the correct i18n package and run the `main.rb` script again it will result in 

```
Bundler::GemNotFound: Could not find multi_json-1.8.2 in any of the sources`
```

Bundle documentation [said](http://bundler.io/v1.10/man/bundle-install.1.html#THE-GEMFILE-LOCK) that,

> THE GEMFILE.LOCK
> 
> When you run bundle install, Bundler will persist the full names and versions of all gems that you used (including dependencies of the gems specified in the Gemfile(5)) into a file called Gemfile.lock.
> 
> Bundler uses this file in all subsequent calls to bundle install, which guarantees that you always use the same exact code, even as your application moves across machines.
> 
> Because of the way dependency resolution works, even a seemingly small change (for instance, an update to a point-release of a dependency of a gem in your Gemfile(5)) can result in radically different gems being needed to satisfy all dependencies.
> 
> As a result, you SHOULD check your Gemfile.lock into version control. If you do not, every machine that checks out your repository (including your production server) will resolve all dependencies again, which will result in different versions of third-party code being used if any of the gems in the Gemfile(5) or any of their dependencies have been updated.

Without due respect, I hope that if you still develop this or have development machine contain the source, you can push the `Gemfile.lock` to the repository, so other can deploy the same gem versions in their machine.

_Edit_
Software Environment,
- ruby

```
2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
```
- jruby

```
9.0.1.0 (2.2.2) 2015-09-02 583f336 OpenJDK 64-Bit Server VM 24.85-b03 on 1.7.0_85-b01 +jit [linux-amd64]
```
- Java version,

```
java version "1.7.0_85"
OpenJDK Runtime Environment (IcedTea 2.6.1) (Arch Linux build 7.u85_2.6.1-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)
```
- Installed gems,

```
activesupport (4.2.4, 3.2.13)
addressable (2.3.8, 2.3.5)
atomic (1.1.99 java, 1.1.14 java)
bio (1.5.0, 1.4.3.0001, 1.4.3)
builder (3.2.2)
bundle (0.0.1)
bundler (1.10.6)
closure-compiler (1.1.11)
color (1.7.1, 1.4.2)
cucumber (2.1.0, 1.3.8)
cucumber-core (1.3.0)
diff-lcs (1.2.5, 1.2.4)
docile (1.1.5)
factory_girl (4.5.0)
faraday (0.8.10, 0.8.8)
fastercsv (1.5.5)
ffi (1.9.10 java)
ffi-compiler (0.1.3)
gherkin (2.12.2 java, 2.12.1 java)
gherkin3 (3.1.1)
git (1.2.9.1, 1.2.6)
github_api (0.10.1)
hashie (3.4.2, 2.0.5)
highline (1.7.6, 1.6.19)
hotwater (0.1.2)
httpauth (0.2.0)
i18n (0.7.0, 0.6.1)
jar-dependencies (0.1.15)
jbundle (0.1.4)
jbundler (0.4.3)
jeweler (1.8.8, 1.8.7)
jruby-openssl (0.9.11 java)
json (1.8.3 java, 1.8.0 java)
jwt (1.5.1, 0.1.8)
maven-tools (0.32.5)
minitest (5.8.0, 5.4.1)
multi_json (1.11.2, 1.8.2)
multi_test (0.1.2, 0.0.2)
multi_xml (0.5.5)
multipart-post (1.2.0)
nokogiri (1.5.10 java)
oauth2 (1.0.0, 0.9.2)
pdf-writer (1.1.8)
power_assert (0.2.4, 0.2.3)
psych (2.0.15 java)
rack (1.6.4, 1.5.2)
rake (10.4.2, 10.1.0)
rdoc (4.2.0, 4.1.0, 3.12.2)
rspec (3.3.0, 2.14.1)
rspec-core (3.3.2, 2.14.5)
rspec-expectations (3.3.1, 2.14.2)
rspec-mocks (3.3.2, 2.14.3)
rspec-support (3.3.0)
ruby-band (0.1.13)
ruby-maven (3.3.3, 3.0.4.1.4)
ruby-maven-libs (3.3.3)
ruport (1.6.3)
shoulda (3.5.0)
shoulda-context (1.2.1, 1.1.5)
shoulda-matchers (2.8.0, 2.3.0)
simplecov (0.10.0, 0.7.1)
simplecov-html (0.10.0, 0.7.1)
test-unit (3.1.3, 3.0.3, 2.5.5)
thor (0.19.1, 0.18.1)
thread_safe (0.3.5 java)
transaction-simple (1.4.0.2)
tzinfo (1.2.2)
wikipedia-vandalism_detection (0.0.1)
```

**Comment by paulgoetze** [comment]
Thanks for reporting and sorry for the late reply - I've been a bit busy the last days.
I also tried to install the gem in an untouched JRuby 1.7.19 environment running on Java SE Runtime Environment build 1.8.0_25-b17 (on a Mac) - and I had exactly the same problems as you have described. 

It looks like the dependencies defined in the gemspec and the dependencies in the ruby-band gem do not want to go together aynmore. Also proper versions are missing in the wikipedia-vandalism_detection gemspec.

Regarding the Gemfile.lock: 
It's not good practice to check in the Gemfile.lock for a gem. You can read more about it here: http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

Yet I will have a look at how this could be fixed during the next days.

**Comment by paulgoetze** [comment]
@shuLhan After some investigation and fixes I figured out at least one setup that seems to work:

* I used **jruby v1.7.19** with Ruby language level **1.9** and the the **Oracle Java jdk1.7.0_79**  
  (I think I remember having issues in the past with OpenJDK in general as well as with version Java JDK 8 in both Oracle and OpenJDK)

I used RVM for installing JRuby: `rvm install jruby-1.7.19 --1.9`

I also did some things in the past to address installation issues - you could use my fixes for `wikipedia-vandalism_detection` from here:  
https://github.com/paulgoetze/wikipedia-vandalism-detection/tree/develop (develop branch)

If you download this gem and then install it manually it should work.
```
$ git clone -b develop git@github.com:paulgoetze/wikipedia-vandalism-detection.git
$ cd wikipedia-vandalism-detection # move to directory 
$ bundle install # installs dependencies
$ rake install # installs the gem locally
```
This branch uses the develop branch of a [fixed ruby-band version](https://github.com/paulgoetze/ruby-band/tree/develop) which you can find in my account (which is unfortunately not available with `gem install`)

I will see what I can do, to get it running as a packaged gem that can be used via rubygems as soon as possible.

Let me know whether this works for you.
